version: "3"

services:
  db:
    image: mysql
    container_name: mysql-batch
    ports:
      - "3306:3306"
    # -e 옵션
    environment:
      # MYSQL 패스워드 설정 가옵션
      MYSQL_ROOT_PASSWORD: "toor"
    # 명령어 실행 (한글 인코딩 관련)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    platform: linux/x86_64