spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

logging:
  level:
    org:
      springframework:
        batch: DEBUG
